deploy:
  provider: s3
  access_key_id: "AKIAIXXFKSRN2BLIFZEA"
  secure: "uZZ1w4gcfXS4g4KniTkjOZ7pF9dZciInl5Gd8jS9eMeMG6UH8BVwqkTWDV3dJr7+92ty8RNOIFcMBWo8/5wjlNaS1wnRzFhoYjr2gIJLgXdHqBtnRp2D7U2Z4TZF1c0mojR4pPiInHbGdj53Us+EtGdscPbiV6bQpVFARGJlSJkfdCgVJHYQRVZp3egM6Vy1K9EuulNDP2c/JK52d0jrux2iXg2Tj5QTopgJZebqG9QrmF4z3vE88vi9MERF1SzB5h6hchT/4/hvT9cC1B/9gLSxZ+D6s3GTcD+Y1LRil4c+YUm7RdgjkWqynytiZnrBWD+ZyH6fReC9ieU1mQxdFpklf0ofdo2cJioHtoN+1Sr3RuoEmjsV1bSyI552GGxdiRki0OoQeLOhFOHaCSHYS3J3dtY2HBMZz/YAjBWLsxwNv4rjA1XuqgyV1sHtYmfHh8xqkgZ9Pyh7eaAG6wUUN8Ak3fDpCFv5hOOPbMwsq1SLHJjJy8/iWC9kLeTNeY44N2xOcN3Jir3meyC8a4SJKu7ayCjO7oNqynKsAOc1WJcFnNGdkJe4yeolNyk8GzADWVAfQB+kd1HkjfGyIImyB0xPBNZ4YsaM7dWqfH23bEHk+KOp969wWjA/AuCCDRCPdPNVjerkRMmULIshhYZa5mJYXr6ob+nTwCmIX5eHBfo="
  bucket: "test2.aarrestad.com"
  skip_cleanup: true
  acl: public_read
  region: eu-west-1