language: c
script: true
deploy:
  provider: s3
  access_key_id:
    secure: "K6Rg5e0u3uqEGL9UJhjd9v4p2Xy2Za5zWMjJrFfBMN6C/y+EQuePWxN1jrJhCnbtMfvFu9FuGklx9DTbFL6cV/FYTNPd8cbpDMUnrVJjxF2+dybwEYivnSJgpyGUVk4e/KW9hIbH25E3o7bVkf8YHBDMGhjDTXbFt0uK9da8K9QibWG2i6EPwGVrgCkj8WgclhJPJuKZswHqNRgAu6lafkT+q3JFdnglSjGxBi1LueAm5JZrFpwVD0oxFhx/uyy7NeAUysDB5WOPqG9JTJPOCsCKn1nTSqcILOMS17T1+cv6HzkCkcJwGQNZcQlaa+ogPkQkjcntz6x7rTN6H5IomXC6V2BffxbJkrtZLq09UThjXxZTW8wnyChySI2qjCUUsJUIXgpIHElVwGiYqSfmpYPVQGenfWfbNlRqBZyDzZAjXAUmKYiUz9ekgesP7jirBsnp/7dWKWduTWvHp1KmJ97XiaqpdCpzyEIw7H9kAWx3Br7mEagEQgo/vV8hu8bHlR983esAuFhJtAoHGGqWDwsMnQI5az5CDlmZ6A66DKKIcn93Usb5JkpNHvFVHkxDV2JLfKK7EZBgoaDmqAQH7CqTRNaD+z+hVzc5RYITALSoT37hDGPyLjztd9W6jt3DLQzwoqAIKB9+AKDs1dq4WtXcvhy204lmx4xzTDkxZHs="
  secret_access_key:
    secure: "Ba1RXz/LNPtofxQIpX4vLeHJwH6TT4IAwjIPWRrOfClXKrRnTe/QT7X8dyvNXhgi28zUZWDsqixmQBZFL5HpO0Q5vpMO2ol+Mq7LN+xl9+YrzKPgkUhURn2CAj9+enjgo7xmpe/HnA+WGX8GfXWJh0gUPsg5dkf99KnYi+2OYAynjyZFKbnHr5TUvN8fMe2cGxqrxQQVMSRVpsGh0z2elktMslbhC78LX131U4+hhDvni6Td4pt+Ezop7r+yw8xI1XI0MHUTZAzVKJSCH3KL7Y+/FHBDTSKfda7ejflzXwhVCDnOaYAY7izvG2aepZMTkvKuSLJazXpz+9Zhhg+iuKcEteDp682C9PtXDPOkyCi5dftDhofGGi47/GlqGxvP3FGd7bVK3QfwBgvuS3upXaS21uYUi/h8dFTGB8Mbhd9GE9VySH33QaHH2DLCsmrd4EdsB2tRhefA6oX7YBiTxYW93YMGlJDYOf7iSSOpix9VMV5gwlsx0vaHaUqZfjL4bBsqWunoyCecn3CYlLYf6q6Icn5e0PEfR41gdcXIXmwZGVznNxmrVJTrfPEL1r3T5QklpBnUWpR9Lcp+vFCRNb6ddH3oPqEGpswpGD/oHLbF30K2xBIl/ZWNBPaKfspLHV6oD0fzo9L0EN4PtGsN6iT0qRkRh0+2por67O0qi3I="
  bucket: "test2.aarrestad.com"
  skip_cleanup: true
  acl: public_read
  region: eu-west-1

